name: Node.js CI

on:
  push:
    branches:
    - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cp CNAME public/

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        target_branch: master
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
